name: app
dependencies:
  - python=3.6
  - psycopg2
  - pip
  - pip:
    - coreapi==2.3.3
    - Django==2.2.2
    - flake8
    - djangorestframework==3.9.4
    - djangorestframework-simplejwt==4.3.0
    - django-annoying==0.10.4
    - drf-writable-nested==0.5.1
    - django-post-office==3.2.1
#    - django-cron==0.5.1
